# Generated by Django 4.2.11 on 2024-03-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('s', 'Salary'), ('o', 'Other')], default='s', help_text='Source type', max_length=1)),
            ],
            options={
                'db_table': 'income',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=300)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category')),
            ],
            options={
                'db_table': 'expense',
            },
        ),
    ]
